package wueffi.taskmanager.client;

import net.minecraft.client.gui.GuiGraphicsExtractor;
import wueffi.taskmanager.client.util.ConfigManager;

final class SettingsTabRenderer {

    private SettingsTabRenderer() {
    }

    static void render(TaskManagerScreen screen, GuiGraphicsExtractor ctx, int x, int y, int w, int h, int mouseX, int mouseY) {
        var textRenderer = screen.uiTextRenderer();
        screen.beginFullPageScissor(ctx, x, y, w, h);
        int left = x + TaskManagerScreen.PADDING;
        int top = screen.getFullPageScrollTop(y);
        ctx.text(textRenderer, "Settings", left, top, TaskManagerScreen.TEXT_PRIMARY, false);
        top += 18;
        ctx.text(textRenderer, "Attribution", left, top, TaskManagerScreen.TEXT_PRIMARY, false);
        screen.drawTopChip(ctx, left + 104, top - 2, 108, 16, screen.attributionHelpOpen);
        ctx.text(textRenderer, "Open Guide", left + 132, top + 2, screen.attributionHelpOpen ? TaskManagerScreen.TEXT_PRIMARY : TaskManagerScreen.TEXT_DIM, false);
        top += 18;
        top = screen.renderWrappedText(ctx, left, top, w - 24, "Raw keeps direct ownership separate. Effective folds shared/runtime buckets back into mods for easier ranking. Use Open Guide for the full measured / inferred / estimated explanation.", TaskManagerScreen.TEXT_DIM) + 10;
        screen.drawSettingRow(ctx, left, top, w - 24, "Session Logging", ProfilerManager.getInstance().isSessionLogging() ? "On" : "Off", mouseX, mouseY);
        top += 22;
        screen.drawSettingRow(ctx, left, top, w - 24, "Session Duration", ConfigManager.getSessionDurationSeconds() + "s", mouseX, mouseY);
        top += 22;
        screen.drawSettingRow(ctx, left, top, w - 24, "Metrics Update Interval", ConfigManager.getMetricsUpdateIntervalMs() + "ms", mouseX, mouseY);
        top += 22;
        screen.drawSettingRow(ctx, left, top, w - 24, "Profiler Update Delay", ConfigManager.getProfilerUpdateDelayMs() + "ms", mouseX, mouseY);
        top += 32;
        ctx.text(textRenderer, "HUD Settings", left, top, TaskManagerScreen.TEXT_PRIMARY, false);
        top += 18;
        screen.drawSettingRow(ctx, left, top, w - 24, "Enabled", ConfigManager.isHudEnabled() ? "Yes" : "No", mouseX, mouseY);
        top += 22;
        screen.drawSettingRow(ctx, left, top, w - 24, "Position", String.valueOf(ConfigManager.getHudPosition()), mouseX, mouseY);
        top += 22;
        screen.drawSettingRow(ctx, left, top, w - 24, "Layout", String.valueOf(ConfigManager.getHudLayoutMode()), mouseX, mouseY);
        top += 22;
        screen.drawSettingRow(ctx, left, top, w - 24, "Trigger Mode", String.valueOf(ConfigManager.getHudTriggerMode()), mouseX, mouseY);
        top += 22;
        screen.drawSettingRowWithTooltip(ctx, left, top, w - 24, "Target FPS", ConfigManager.getFrameBudgetTargetFps() + " FPS", mouseX, mouseY, "Sets the frame-budget target used by the HUD, alerts, and exports when judging whether a frame is over budget.");
        top += 22;
        screen.drawSliderSetting(ctx, left, top, w - 24, "HUD Transparency", ConfigManager.getHudTransparencyPercent(), mouseX, mouseY);
        top += 24;
        screen.drawSettingRow(ctx, left, top, w - 24, "HUD Mode", String.valueOf(ConfigManager.getHudConfigMode()), mouseX, mouseY);
        top += 22;
        if (ConfigManager.getHudConfigMode() == ConfigManager.HudConfigMode.PRESET) {
            screen.drawSettingRow(ctx, left, top, w - 24, "Preset", String.valueOf(ConfigManager.getHudPreset()), mouseX, mouseY);
            top += 22;
            screen.drawSettingRow(ctx, left, top, w - 24, "Expand On Warning", ConfigManager.isHudExpandedOnWarning() ? "On" : "Off", mouseX, mouseY);
            top += 22;
            screen.drawSettingRowWithTooltip(ctx, left, top, w - 24, "Budget Color Mode", ConfigManager.isHudBudgetColorMode() ? "On" : "Off", mouseX, mouseY, "Colors HUD rows by pressure so frame, tick, VRAM, and latency problems are easier to spot.");
            top += 22;
            screen.drawSettingRowWithTooltip(ctx, left, top, w - 24, "Auto-Focus Alert", ConfigManager.isHudAutoFocusAlertRow() ? "On" : "Off", mouseX, mouseY, "Pins the strongest current issue to the top of the HUD instead of making you scan every row.");
            top += 20;
            ctx.text(textRenderer, textRenderer.plainSubstrByWidth("Preset mode drives the HUD contents for you. Switch HUD Mode to CUSTOM to pick individual sections.", w - 24), left, top, TaskManagerScreen.TEXT_DIM, false);
            top += 34;
        } else {
            screen.drawSettingRow(ctx, left, top, w - 24, "FPS", ConfigManager.isHudShowFps() ? "On" : "Off", mouseX, mouseY);
            top += 22;
            screen.drawSettingRow(ctx, left, top, w - 24, "Frame Stats", ConfigManager.isHudShowFrame() ? "On" : "Off", mouseX, mouseY);
            top += 22;
            screen.drawSettingRow(ctx, left, top, w - 24, "Tick Stats", ConfigManager.isHudShowTicks() ? "On" : "Off", mouseX, mouseY);
            top += 22;
            screen.drawSettingRow(ctx, left, top, w - 24, "Utilization", ConfigManager.isHudShowUtilization() ? "On" : "Off", mouseX, mouseY);
            top += 22;
            screen.drawSettingRow(ctx, left, top, w - 24, "Temperatures", ConfigManager.isHudShowTemperatures() ? "On" : "Off", mouseX, mouseY);
            top += 22;
            screen.drawSettingRow(ctx, left, top, w - 24, "Parallelism", ConfigManager.isHudShowParallelism() ? "On" : "Off", mouseX, mouseY);
            top += 22;
            screen.drawSettingRow(ctx, left, top, w - 24, "Logic", ConfigManager.isHudShowLogic() ? "On" : "Off", mouseX, mouseY);
            top += 22;
            screen.drawSettingRow(ctx, left, top, w - 24, "Background", ConfigManager.isHudShowBackground() ? "On" : "Off", mouseX, mouseY);
            top += 22;
            screen.drawSettingRowWithTooltip(ctx, left, top, w - 24, "Frame Budget", ConfigManager.isHudShowFrameBudget() ? "On" : "Off", mouseX, mouseY, "Shows the latest frame time against your configured target FPS budget and how far over or under budget it is.");
            top += 22;
            screen.drawSettingRow(ctx, left, top, w - 24, "Memory", ConfigManager.isHudShowMemory() ? "On" : "Off", mouseX, mouseY);
            top += 22;
            screen.drawSettingRowWithTooltip(ctx, left, top, w - 24, "VRAM", ConfigManager.isHudShowVram() ? "On" : "Off", mouseX, mouseY, "Shows GPU memory use and paging pressure when the driver exposes VRAM counters.");
            top += 22;
            screen.drawSettingRowWithTooltip(ctx, left, top, w - 24, "Network", ConfigManager.isHudShowNetwork() ? "On" : "Off", mouseX, mouseY, "Shows inbound and outbound throughput so server and packet spikes are easier to correlate.");
            top += 22;
            screen.drawSettingRowWithTooltip(ctx, left, top, w - 24, "Chunk Activity", ConfigManager.isHudShowChunkActivity() ? "On" : "Off", mouseX, mouseY, "Tracks chunk generation, meshing, and upload pressure in the HUD.");
            top += 22;
            screen.drawSettingRow(ctx, left, top, w - 24, "World", ConfigManager.isHudShowWorld() ? "On" : "Off", mouseX, mouseY);
            top += 22;
            screen.drawSettingRow(ctx, left, top, w - 24, "Disk I/O", ConfigManager.isHudShowDiskIo() ? "On" : "Off", mouseX, mouseY);
            top += 22;
            screen.drawSettingRowWithTooltip(ctx, left, top, w - 24, "Input Latency", ConfigManager.isHudShowInputLatency() ? "On" : "Off", mouseX, mouseY, "Shows the latest presented input latency beside the rest of the live performance metrics.");
            top += 22;
            screen.drawSettingRow(ctx, left, top, w - 24, "Session Status", ConfigManager.isHudShowSession() ? "On" : "Off", mouseX, mouseY);
            top += 22;
            screen.drawSettingRow(ctx, left, top, w - 24, "Expand On Warning", ConfigManager.isHudExpandedOnWarning() ? "On" : "Off", mouseX, mouseY);
            top += 22;
            screen.drawSettingRowWithTooltip(ctx, left, top, w - 24, "Budget Color Mode", ConfigManager.isHudBudgetColorMode() ? "On" : "Off", mouseX, mouseY, "Colors HUD rows by pressure so frame, tick, VRAM, and latency problems are easier to spot.");
            top += 22;
            screen.drawSettingRowWithTooltip(ctx, left, top, w - 24, "Auto-Focus Alert", ConfigManager.isHudAutoFocusAlertRow() ? "On" : "Off", mouseX, mouseY, "Pins the strongest current issue to the top of the HUD instead of making you scan every row.");
            top += 20;
        }
        ctx.text(textRenderer, "HUD Rate Of Change", left, top, TaskManagerScreen.TEXT_PRIMARY, false);
        top += 18;
        screen.drawSettingRow(ctx, left, top, w - 24, "Display Zero Rates", ConfigManager.isHudShowZeroRateOfChange() ? "On" : "Off", mouseX, mouseY);
        top += 22;
        screen.drawSettingRow(ctx, left, top, w - 24, "FPS Rates", ConfigManager.isHudShowFpsRateOfChange() ? "On" : "Off", mouseX, mouseY);
        top += 22;
        screen.drawSettingRow(ctx, left, top, w - 24, "Frame Rates", ConfigManager.isHudShowFrameRateOfChange() ? "On" : "Off", mouseX, mouseY);
        top += 22;
        screen.drawSettingRow(ctx, left, top, w - 24, "Tick Rates", ConfigManager.isHudShowTickRateOfChange() ? "On" : "Off", mouseX, mouseY);
        top += 22;
        screen.drawSettingRow(ctx, left, top, w - 24, "Utilization Rates", ConfigManager.isHudShowUtilizationRateOfChange() ? "On" : "Off", mouseX, mouseY);
        top += 22;
        screen.drawSettingRow(ctx, left, top, w - 24, "Memory Rates", ConfigManager.isHudShowMemoryAllocationRate() ? "On" : "Off", mouseX, mouseY);
        top += 22;
        screen.drawSettingRow(ctx, left, top, w - 24, "VRAM Rates", ConfigManager.isHudShowVramRateOfChange() ? "On" : "Off", mouseX, mouseY);
        top += 22;
        screen.drawSettingRow(ctx, left, top, w - 24, "Network Rates", ConfigManager.isHudShowNetworkRateOfChange() ? "On" : "Off", mouseX, mouseY);
        top += 22;
        screen.drawSettingRow(ctx, left, top, w - 24, "Chunk Activity Rates", ConfigManager.isHudShowChunkActivityRateOfChange() ? "On" : "Off", mouseX, mouseY);
        top += 22;
        screen.drawSettingRow(ctx, left, top, w - 24, "World Rates", ConfigManager.isHudShowWorldRateOfChange() ? "On" : "Off", mouseX, mouseY);
        top += 22;
        screen.drawSettingRow(ctx, left, top, w - 24, "Disk I/O Rates", ConfigManager.isHudShowDiskIoRateOfChange() ? "On" : "Off", mouseX, mouseY);
        top += 22;
        screen.drawSettingRow(ctx, left, top, w - 24, "Input Latency Rates", ConfigManager.isHudShowInputLatencyRateOfChange() ? "On" : "Off", mouseX, mouseY);
        top += 32;
        ctx.text(textRenderer, "In-Game Alerts", left, top, TaskManagerScreen.TEXT_PRIMARY, false);
        top += 18;
        screen.drawSettingRowWithTooltip(ctx, left, top, w - 24, "Enabled", ConfigManager.isPerformanceAlertsEnabled() ? "On" : "Off", mouseX, mouseY, "Turns lightweight performance warnings on while you play, even if the full HUD is hidden.");
        top += 22;
        screen.drawSettingRowWithTooltip(ctx, left, top, w - 24, "Chat Messages", ConfigManager.isPerformanceAlertChatEnabled() ? "On" : "Off", mouseX, mouseY, "Also posts a short chat line when a sustained frame-time or MSPT breach is detected.");
        top += 22;
        screen.drawSettingRowWithTooltip(ctx, left, top, w - 24, "Frame Threshold", ConfigManager.getPerformanceAlertFrameThresholdMs() + " ms", mouseX, mouseY, "If frame time stays above this threshold for the configured number of consecutive ticks, the overlay banner and optional chat alert fire.");
        top += 22;
        screen.drawSettingRowWithTooltip(ctx, left, top, w - 24, "Server MSPT Threshold", ConfigManager.getPerformanceAlertServerThresholdMs() + " ms", mouseX, mouseY, "If integrated-server MSPT stays above this threshold for the configured number of consecutive ticks, a live alert is raised.");
        top += 22;
        screen.drawSettingRowWithTooltip(ctx, left, top, w - 24, "Consecutive Ticks", Integer.toString(ConfigManager.getPerformanceAlertConsecutiveTicks()), mouseX, mouseY, "Requires sustained pressure for this many consecutive ticks before alerting so transient one-off spikes do not spam you.");
        top += 32;
        ctx.text(textRenderer, "Table Columns", left, top, TaskManagerScreen.TEXT_PRIMARY, false);
        top += 18;
        screen.drawSettingRow(ctx, left, top, w - 24, "Tasks: %CPU", ConfigManager.isTasksColumnVisible("cpu") ? "On" : "Off", mouseX, mouseY);
        top += 22;
        screen.drawSettingRow(ctx, left, top, w - 24, "Tasks: Threads", ConfigManager.isTasksColumnVisible("threads") ? "On" : "Off", mouseX, mouseY);
        top += 22;
        screen.drawSettingRow(ctx, left, top, w - 24, "Tasks: Samples", ConfigManager.isTasksColumnVisible("samples") ? "On" : "Off", mouseX, mouseY);
        top += 22;
        screen.drawSettingRow(ctx, left, top, w - 24, "Tasks: Invokes", ConfigManager.isTasksColumnVisible("invokes") ? "On" : "Off", mouseX, mouseY);
        top += 22;
        screen.drawSettingRow(ctx, left, top, w - 24, "GPU: %GPU", ConfigManager.isGpuColumnVisible("pct") ? "On" : "Off", mouseX, mouseY);
        top += 22;
        screen.drawSettingRow(ctx, left, top, w - 24, "GPU: Threads", ConfigManager.isGpuColumnVisible("threads") ? "On" : "Off", mouseX, mouseY);
        top += 22;
        screen.drawSettingRow(ctx, left, top, w - 24, "GPU: Est ms", ConfigManager.isGpuColumnVisible("gpums") ? "On" : "Off", mouseX, mouseY);
        top += 22;
        screen.drawSettingRow(ctx, left, top, w - 24, "GPU: R.S", ConfigManager.isGpuColumnVisible("rsamples") ? "On" : "Off", mouseX, mouseY);
        top += 22;
        screen.drawSettingRow(ctx, left, top, w - 24, "Memory: CLS", ConfigManager.isMemoryColumnVisible("classes") ? "On" : "Off", mouseX, mouseY);
        top += 22;
        screen.drawSettingRow(ctx, left, top, w - 24, "Memory: MB", ConfigManager.isMemoryColumnVisible("mb") ? "On" : "Off", mouseX, mouseY);
        top += 22;
        screen.drawSettingRow(ctx, left, top, w - 24, "Memory: %", ConfigManager.isMemoryColumnVisible("pct") ? "On" : "Off", mouseX, mouseY);
        top += 32;
        ctx.text(textRenderer, "Graph Colours", left, top, TaskManagerScreen.TEXT_PRIMARY, false);
        top += 18;
        screen.drawSettingRow(ctx, left, top, w - 24, "CPU Colour", screen.focusedColorSetting == TaskManagerScreen.ColorSetting.CPU ? screen.colorEditValue + "_" : screen.getColorSettingHex(TaskManagerScreen.ColorSetting.CPU), mouseX, mouseY);
        top += 22;
        screen.drawSettingRow(ctx, left, top, w - 24, "GPU Colour", screen.focusedColorSetting == TaskManagerScreen.ColorSetting.GPU ? screen.colorEditValue + "_" : screen.getColorSettingHex(TaskManagerScreen.ColorSetting.GPU), mouseX, mouseY);
        top += 22;
        screen.drawSettingRow(ctx, left, top, w - 24, "World Entities Colour", screen.focusedColorSetting == TaskManagerScreen.ColorSetting.WORLD_ENTITIES ? screen.colorEditValue + "_" : screen.getColorSettingHex(TaskManagerScreen.ColorSetting.WORLD_ENTITIES), mouseX, mouseY);
        top += 22;
        screen.drawSettingRow(ctx, left, top, w - 24, "Loaded Chunks Colour", screen.focusedColorSetting == TaskManagerScreen.ColorSetting.WORLD_CHUNKS_LOADED ? screen.colorEditValue + "_" : screen.getColorSettingHex(TaskManagerScreen.ColorSetting.WORLD_CHUNKS_LOADED), mouseX, mouseY);
        top += 22;
        screen.drawSettingRow(ctx, left, top, w - 24, "Rendered Chunks Colour", screen.focusedColorSetting == TaskManagerScreen.ColorSetting.WORLD_CHUNKS_RENDERED ? screen.colorEditValue + "_" : screen.getColorSettingHex(TaskManagerScreen.ColorSetting.WORLD_CHUNKS_RENDERED), mouseX, mouseY);
        top += 22;
        screen.drawSettingRow(ctx, left, top, w - 24, "Reset Graph Colours", "Defaults", mouseX, mouseY);
        top += 20;
        ctx.text(textRenderer, textRenderer.plainSubstrByWidth("Click a colour row, type a hex value like #5EA9FF, then press Enter to save.", w - 24), left, top, TaskManagerScreen.TEXT_DIM, false);
        ctx.disableScissor();
    }
}
